spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.zjwpwmqnqwkxidkzxwkn
spring.datasource.password=RAMsarii2026
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
gemini.api.key=AIzaSyDQdqKh9z3uKrDXtQeY803XxDRCvrVnZ7I
gemini.api.key.matchmaking=AIzaSyBjLQu3NvJbtgSylrR22NQRYQmtUJEvPrk
gemini.api.key.chat=AIzaSyAJ2kf2ckfIRBi2B1VZXy6UZCpLRjTpGyQ